### ISSUE TITLE
Album fotografií

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#10]
Je třeba vymyslet a zprovoznit Album fotografií. Dle základní představy má uživatel vkládat obsah typu Obrázek nebo Video a ten přiřadit do Alb fotografií, přičemž alba by byla pevně řízena jedinou autoritou, aby nevznikaly "ghost structures". V rámci každého alba by pak mohla být možnost filtrace, např. dle autora.

**Comment by Yendy** [comment]
Velmi univerzálně vypadá modul Media https://www.drupal.org/project/media, který mj. umí tahat fotky a videa napříč internetem (internet browser), což je sice spíše nežádoucí vlastnost, ale princip modulu by mohl napomoci - vyzkoušet!

**Comment by Yendy** [comment]
Modul Colorbox https://www.drupal.org/project/colorbox je pouze "prohlížeč" nad stránkami s možnostmi navigace mezi obrázky a jejich popisem. V případě absence komplexnějšího nástroje by mohl vyhovovat.

**Comment by Yendy** [comment]
Modul Media je schovaný v systému, objevuje se např. při zadávání specifického obsahu (obrázky, videa, audio, dokumenty), ale jinak nic nezobrazuje! Má užitečnou funkci Mé soubory, ale to je asi tak všechno. V tuto chvíli jsem zcela nepochopil jeho filozofii. Nutno podrobněji prozkoumat, neboť vyžaduje modul file_entity, který umožňuje souborům být viděny - v kostce zajímavější než samotný Media modul.

**Comment by Yendy** [comment]
Vyzkoušen další pochybný modul Brilliant Gallery https://www.drupal.org/project/brilliant_gallery. Sice umí tahat obsah i z Picassy (nepoužitelné), ale čert ví kam! Pravděpodobná cesta půjde přes Views!

**Comment by Yendy** [comment]
Odzkoušeno Views a jeví se zatím nejrozumněji ve spojení nějakého overlay prohlížeče (Colorbox?). Je třeba vyřešit vkládání multiple obrázků!

**Comment by Yendy** [comment]
Potvrzena domněnka s Views - nejlepší ve spojení s Colorbox. Pozor - Colorbox má kromě modulu ještě plugin do libraries https://www.drupal.org/project/libraries!
Dále je třeba vytvořit dynamický obsah galerie (Alba) + různé typy obsahu (Fotografie & Video) + galerii galerií.

**Comment by Yendy** [comment]
Vytvořeno Views/Galerie. Zatím bez filtrace obsahu, připojeno k typu obsahu Tábory jako Block.

**Comment by kalich5** [comment]
Super, vidím že se posouváme. A půjde to pak tagovat?

**Comment by Yendy** [comment]
Vytvořeny bloky pro filtraci obsahu vztaženému k táboru, klubovně. Bloky se zobrazují v obsahu tábor, klubovna. Filtrování probíhá ve Views/Contextual filters.

**Comment by Yendy** [comment]
Tento issue je příliš obsáhlý, rozpadá se na několik inkrementálních částí. Z toho důvodu nyní uzavírám a zároveň otevírám nový s detailnějším zadáním.
