### ISSUE TITLE
První užití po aktivaci účtu

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#14]
"First Use Case". Uživatel po registraci a a úspěšné aktivaci účtu obdrží e-mail s odkazem na první přihlášení. Ten nejspíš nefunguje (dle info od Mamuta i z dalších testovacích účtů), je třeba doladit a odkázat uživatele nejen na změnu hesla, ale zároveň na "Guide", který mu pomůže pochopit možnosti webu.

**Comment by kalich5** [comment]
To by chtělo doladit. Nějakou stránku na webu která by informovala co a jak tam je. Ale celé ty stránky by měly být udělané tak, aby uživatelé nepotřebovali návod na to jak s tím webem.

**Comment by Yendy** [comment]
Kalichu, můžeš se toho ujmout? Sepiš postup, co jako uživatel očekáváš na počátku. Tj. Vyplnění a odeslání registrace 》obdržení emailu o registraci 》potvrzení o aktivaci účtu 》... Napiš podrobně i texty. Díky

**Comment by kalich5** [comment]
Jasný, kouknu na to a něco sepíšu. Ale do finálu to pak dotáhneme až bude vzhled a udělám k tomu i obrázky.

**Comment by Yendy** [comment]
ok

**Comment by kalich5** [comment]
Začínám na tom pracovat.
https://docs.google.com/document/d/1E_pOVzCa3q8E8XzA1qPsJ48P0zi3gmwoa2n63ncR59I/edit

**Comment by Yendy** [comment]
Otestováno. Problém byl v jednorázovém odkazu, který fungoval pouze jednou pro každého nového uživatele. Lze na něj kliknout pouze jednou a zadat heslo. Další přihlášení se provádějí přes tradiční webové rozhraní.
