### ISSUE TITLE
Právní rámec stránek

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#15]
Rozhodnout o existenci nebo přidružení stránek k právnímu subjektu.

**Comment by kalich5** [comment]
Tohle je uzavřené?

**Comment by Yendy** [comment]
Ne, právě to vracím do progresu.

**Comment by Yendy** [comment]
Něco jsme probírali minule, ale formálně to ještě nemáme uzavřené.

**Comment by kalich5** [comment]
Chtělo by se to nějak uzavřít a třeba udělat občanské sdružení. Aby to při startu bylo OK

**Comment by nurmi1357** [comment]
Já navrhuji se dnes u teto věci dohodnout, jak to formálně udělat co nejjednodušeji, aby nám to Sova nebo jiný právník schválil. Na spolek bych to zatím nedělal. Stačí 1 nebo 3 provozovatelé webu. Pokud toto téma bude volné, udělám. Těším se na vás. Nurmi

**Comment by Yendy** [comment]
Rozhodnuto, že provozovatelé budou 3 osoby.
