### ISSUE TITLE
Skupina Vylepšování webu

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#20]
Rozhodnout o využití/nevyužití skupiny. V tuto chvíli je názor takový, že skupinu ponecháme pro uživatele, kteří budou mít chuť podílet se svými nápady, částečně volným časem, na vylepšování komunitního webu.

**Comment by kalich5** [comment]
Určitě bych jí udělal a využil bych to.

**Comment by Yendy** [comment]
Kvůli této skupině jsem založil nový typ skupiny "Volná skupina", do které může každý vstupovat a vystupovat bez zásahu vlastníka skupiny. Vlastník skupiny není ani definován, pouze její administrátor a moderátor.
