### ISSUE TITLE
Vymyslet, popsat a nastavit B&R

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#21]
Zjistit přesný stav B&R serveru, na kterém stránky běží a dle toho přizpůsobit vlastní B&R.
Backup bude nutný:
- před každou změnou (aktualizace, přidání modulu, update, upgrade).
- pravidelně minimálně ??? za měsíc.

Backup bude prováděn "Kým" a "Kam"? Kolik kopií backupu bude uchováváno?
Obnova bude prováděna "Jak" a "Kým"? Co bude spouštěčem obnovy?

**Comment by kalich5** [comment]
Jako backup bych dělal při každé změně, a nejlépe aby se to dělalo automaticky. Nešlo by využít nějaké zašifrování a použití třeba něčeho mimo. Vím, že nechceme nic posílat ven, ale v zašifrované podobě by to podle mě neměl být problém.

**Comment by Yendy** [comment]
Nejpoužitelnější automatický backup je Backup and Migrate, https://www.drupal.org/project/backup_migrate . Nicméně potřebuje druhou stranu (SFTP server apod.), na kterou se budou data posílat. Komerční řešení jsou postavena zpravidla na službách amerických serverů, obvykle s malou nebo žádnou garancí kompromitace dat, tj. neakceptovatelná řešení.
Základní požadavky jsou:
- storage umístěná v ČR s garancí nemigrace dat mimo území ČR,
- šifrované disky, šifrovaná data,
- dostatečná konektivita k Petkari.cz,
- ideálně šifrované spojení,
- ideálně český majitel/poskytovatel (minimalizace právních i funkčních "kliček").

**Comment by kalich5** [comment]
My doma máme servery (máme VDSL od O2, a nebo u babičky (tam je UPC). A podle mě s Bratrem budeme schopný udělat nějaký FTP přístup na disky. Třeba 50GB pro začátek a není problém navyšovat

**Comment by Yendy** [comment]
Aktuální stav: nastavili jsme s poskytovatelem webhostingu ústní dohodu. On tak jako tak provádí backup každých 24 hodin s verzováním několika dní na vzdálenou lokalitu. Pokud by došlo k havárii webu nebo špatné manipulaci administrátora, jsme dohodnuti, že na vyžádání web obnoví z jeho záloh.

Zároveň hledáme společné řešení, které bychom měli MY pod kontrolou.

Existují také zálohy, které provádím ručně každých cca 5-10 dní.
