### ISSUE TITLE
Fotografie - přidat tagy

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#23]
Shodli jsme se na tom, že fotografie budou filtrovány buďto dle přednastavených parametrů typu Tábor, Klubovna nebo pomocí tagů. Účel zatím blíže nespecifikován, ponecháno na uživatelích.

**Comment by kalich5** [comment]
Mít u každé nahrané fotografie povinnost zadat nějaký parametr. Aby tam nebyly neurčené a nezařazené fotky

**Comment by Yendy** [comment]
Hotovo. Zatím ponecháno na uživatelích. Každá fotografie má možnost výběru tábora a klubovny, zároveň je volné pole Tagy, kde lze napsat v podstatě cokoli. Bude poté použito v různých filtrech napříč Galerií.
