### ISSUE TITLE
Filtrování obsahu datem - informativně

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#24]
Zapracování fukcionality, která bude filtrovat obsah jiného typu na stránce aktuálního obsahu (např. fotografie z tábora na stránce tábora) dle zadaného data. 

Problém je ten, že ne vždy platí, že pokud byl člen v oddíle od 1983 do 1992, že byl účasten na všech táborech. Stejný problém existuje, pokud bude v budoucnosti seznam všech akcí. Řešení nelze automatizovat a je jen na členovi, aby případný nesoulad editoval ručně. Tj. při založení člena mu budou automaticky přiřazeny tábory z jeho období, on je může v editaci přizpůsobit realitě.

**Comment by kalich5** [comment]
Při zadávání seznamu "všech" akcí bych vycházel ze seznamu docházky (který v kronikách nebo v excelu) a to by mohl zadávat člověk (admin akcí) při aktualizaci. Nabízel by se mu seznam všech potencionálních členů a on by je zaškrtával

**Comment by Yendy** [comment]
Fotografie z tábora na stránce tábora jsme provedli parametrem fotografie "Souvisí s táborem".

Filtrování obsahu dle data nás teprve čeká a bude to předmětem dalších vylepšení (zadám separátní issue).
