### ISSUE TITLE
Vzhled WEBU

### ISSUE THREAD

**Issue by kalich5** [Yendy/petkari.cz#27]
Měli by jsme pomalu začít řešit vzhled. Čas se krátí, a myslím si že to nebude za týden hotový.

**Comment by Yendy** [comment]
Popis a tagy zasahují do pravého sloupce. Web by měl být širší. Osobně kdo je online bych dal do nějaké lišty pod/nad menu. Stejně jako časem by se tam mohlo zobrazovat kdo má svátek a narozeniny.
http://petkari.cz/node/add/fotografie 

A pole "Kdo je nový" bych dal jako je to i třeba na forech do zápatí. (Zadáno Kalichem, přesunuto Yendym)

**Comment by kalich5** [comment]
K vzhledu mám připomínku. Musí být optimalizované zobrazení obrázků táborů viz http://www.petkari.cz/tabory

**Comment by Yendy** [comment]
Řešeno parciálními issues + kompletní přípravou layoutu.
