### ISSUE TITLE
RECaptcha

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#3]
Máme první neoprávněný pokus o přístup - zkusit eliminovat systémem typu Captcha.

**Comment by kalich5** [comment]
Něco takového bych tam dal. Klidně něco jednoduchého. Prostě otázku: Kdy byl založen oddíl" a políčko na rok. To už ti roboti nezvládnou si myslím.

**Comment by Yendy** [comment]
V tuto chvíli není na pořadu dne, jedině v budoucnosti, kdy by mohla tato funkce filtrovat hloupější automaty. Jinou přidanou hodnotu to nemá.
