### ISSUE TITLE
Verze Drupalu

### ISSUE THREAD

**Issue by kalich5** [Yendy/petkari.cz#31]
Jaká je tam použitá verze drupalu? Co jsem tak četl o poslední verzi 8 tak má hodně věcí v sobě. A je fakt rychlá.

**Comment by Yendy** [comment]
1. Tento prostor není pro dotazy, ale pro řešení předem definovaných problémů. Nezadávej je sem, prosím, pošli to raději e-mailem, jinak se tu přestaneme orientovat!
2. Drupal 8 vešel do produkce teprve v lednu 2016 a od té doby vyšlo již větší množství oprav. Zároveň chybí spousta modulů pro verzi 8 nebo jsou v nestabilní vývojové fázi. Proto je Drupal 8 pro naše účely naprosto nevhodný. Jeho přidané funkce jsou pouze implementované již existující moduly (např. Views). Jediná parciální výhoda je MVC framework modulů. S Drupalem 8 počítám, že do něj stránky překlopíme, ale ne dříve než za 1 rok!
