### ISSUE TITLE
Galerie médií

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#33]
V hlavním menu je odkaz Galerie, který zobrazuje všechny vložené fotografie. Bude třeba dořešit "Galerii galerií", tj. tento odkaz by měl otevřít seznam odkazů na jednotlivé "podgalerie". Zatím je návrh strukturovat tyto odkazy dle táborů, příp. kluboven nebo tagů.
Mějme v patrnosti, že jen táborů je 50 a budou se nadále zvyšovat. Stejně tak Tagy jsou v principu neomezené a jejich množství může být tedy nekonečné.
=> Vymyslet omezený počet "podgalerií", ostatní fotografie nabízet raději kontextově u konkrétních akcí, míst, lidí.

**Comment by Yendy** [comment]
Také je třeba v budoucnosti počítat s příspěvky typu video a jejich zakomponování do struktury Galerie.

**Comment by kalich5** [comment]
Já bych řekl, že by na začátku měly být dvě sekce. A to by byla "Chronologická" a "Podle Tagů"

V Chronologické části by byly podsekce Oddílové roky. Jen velká tlačítka na kterých by byly roky. Tedy třeba "1965-1966" atd. A po rozkliknutí by byly jednotlivé generované galerie. Tedy tábory, boje družin, časem i výpravy. Všechno chronologicky jak to v tom roce proběhlo. My teď máme u některých výprav několik podgalerií, když tam třeba fotilo víc lidí. To by podle mě šlo taky nějak zařadit.

A ta část tagová, tam by se zobrazovalo nějaké určitě množství tagů. Nedokážu říct kolik, třeba 50. A to by byly ty automaticky generované. A určitě po každé nějaké nové. Aby se to tam točilo.

**Comment by Yendy** [comment]
Dle data lze vytvářet souhrny, např. seznam měsíců s odkazem na obsah daného měsíce.Vytváří se pomocí Contextual filters (viz Views/Archive).

**Comment by Yendy** [comment]
Přesunuto do dalších etap s podrobnějším zadáním.
