### ISSUE TITLE
Import seznamu členů

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#34]
Počet členů je nad rámec možností manuálního vkládání. Zjistit strukturu databáze příspěvků typu "Člen" a zkusit otestovat import seznamu, např. CSV.

**Comment by kalich5** [comment]
Pošli vzorový CSV soubor a já ti ho naplním daty která budeš chtít.

**Comment by Yendy** [comment]
Import pomocí Feeds + Job Scheduler. Pozor, moduly jsou ve fázi beta + alpha => každý import nejprve otestovat!
