### ISSUE TITLE
Výběr výchozího Theme

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#37]
Klíčové pro vzhled webu je vybrat výchozí téma, které bude přizpůsobeno na míru.
Současné téma je Skeleton, mezi další adepty patří Responsive Blog.

**Comment by kalich5** [comment]
A mohl by jsi na ně dát odkaz?

**Comment by Yendy** [comment]
Responsive blog https://www.drupal.org/project/responsive_blog neplní co slibuje. Nelze jednoduše nastavit jak logo, tak název webu. Obrázky autorů u příspěvků se navzdory nastavení nezobrazují. Není triviální možnost vložení pozadí, vše nutné vytvářet zásahem do kódu (problematické aktualizace). Rovněž stav projektu "Maintenance fixes only" je špatná volba do budoucna.

**Comment by kalich5** [comment]
Jako pokud je vzhled v takovém stavu, tak mi to nepřijde jako dobrá volba. A tím přispůsobováním vytvoříme úplně novou šablonu? Nebo jen odvozenou od původní s plnou podporou aktualizací?

**Comment by Yendy** [comment]
Lze vytvořit "potomka" vzhledu a tím vyřešit i aktualizace přizpůsobeného potomka. To je i naše cesta. V případě Responsive blog je problematická hlavně jeho NEaktualizace. Pokud jednoho dne přejdeme na Drupal 8, měli bychom být schopni se vším všudy. Hledám dál. Pokud chceš, pak na https://www.drupal.org/project/project_theme lze vybírat témata. Ovšem bez nahrání na web a laborací s tématem se toho moc nedozvíš :-(.

**Comment by kalich5** [comment]
Tak to znám :-) "potomka" nebo "Child themes" má i WordPress a používáme to na oddílovém webu.

Na ty šablony kouknu, co by se našlo. Já teď žádný drupal nainstalovaný nemám no. Tak asi podle toho co nejdu, tak dám odkaz sem.

**Comment by Yendy** [comment]
Stav grafiky webu je "uspokojivý". Změnil jsem úvodní fotku, která se již neztrojuje při prohlížení na malých obrazovkách (mobily). Drobné vady v zobrazení zkusíme opravit, ale nejsou prioritou.

Do budoucnosti design překopeme se vším všudy, od grafického návrhu až po vrstvy layoutu.
