### ISSUE TITLE
Překlad rozhraní

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#38]
Zde uvádějte všechny nalezené nepřeložené části webu.

**Comment by Yendy** [comment]
Při vkládání fotografie nejsou přeloženy "Browse..." a "No file selected." Nenalezeno standardní cestou překladu, nutné zapátrat v databázi a v kódu.

**Comment by kalich5** [comment]
Popis a tagy zasahují do pravého sloupce. Web by měl být širší. Osobně kdo je online bych dal do nějaké lišty pod/nad menu. Stejně jako časem by se tam mohlo zobrazovat kdo má svátek a narozeniny.
http://petkari.cz/node/add/fotografie 

A pole "Kdo je nový" bych dal jako je to i třeba na forech do zápatí.

> Toto patří do Vzhled webu, nikoli do Překlad rozhraní - přesunul jsem to tam.

**Comment by kalich5** [comment]
http://petkari.cz/user/13/group/invite

You do not have any pending group invitations.

**Comment by Yendy** [comment]
Přeloženo rozhraní vkládání zájmové skupiny.

**Comment by Yendy** [comment]
Opraveno "You do not have any pending group invitations." - viz výše.

**Comment by Yendy** [comment]
Opraveno celé rozhraní podskupin (zájmových skupin). Add member, Invite member atd.

**Comment by Yendy** [comment]
Popisy při vkládání přílohy se tahají přímo z browseru, záleží na jeho nastavení. Na straně webu není mechanismus, jak texty jednoduše "podsunout".
