### ISSUE TITLE
Terms of Use

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#4]
Podmínky užívání webu (modul Terms of Use) jsou nepřizpůsobivé. Nelze upravit jejich prezentaci na stránce nového uživatele a v systému nelze nikde najít, kdo s nimi souhlasil nebo ne (de facto s nimi souhlasili všichni, kdo provedli registraci, může se ale stát, že jej zadá administrátor přímo a pak bude užívat web aniž by se seznámil a odsouhlasil jeho Terms).
Prezentaci lze zkusit přizpůsobit modulem Panels, souhlas však ne.

**Comment by kalich5** [comment]
Můžu nějaký vyšší přístup do toho webu. A nějaké odkazy na to, kde jsou třeba moduly pro Drupal. Znám pořádně jen WordPress a tam je veliký repozitář s pluginy (moduly)

**Comment by Yendy** [comment]
Případné další úpravy budou probíhat v Code.
