### ISSUE TITLE
Tagy

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#51]
Zprovoznit tagy. V současnosti jsou neživé. Nejspíš bude třeba lépe popsat jejich používání.

**Comment by Yendy** [comment]
Typy obsahu Příspěvek a Fotografie překlopeny na interaktivní Tagy. Nyní se u každého obsahu objevují tagy jako odkazy.
Zároveň jsem popsal v nápovědě políčka, jak jednotlivé položky v tagu oddělovat.

**Comment by kalich5** [comment]
Super, všimnul jsem si toho už odpoledne. Hned to tomu webu dalo další rozměr :-)
