### ISSUE TITLE
Vytvoření a poslání pozvánky.

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#58]
Text pozvánky zaslat pomocí všech kanálů, tj. pětkařská konference, facebook, google+.

**Comment by kalich5** [comment]
Na FB jsem dal krátký text a odkaz na web. Jinak do konference starých pušek by se to mělo určitě poslat

**Comment by Yendy** [comment]
Dohodnuty pravidelné občerstvovací maily.
