### ISSUE TITLE
Konečný počet účastníků

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#59]
Stanovit dle zájemců konečný počet účastníků, kteří pojedou alespoň na 95%.

**Comment by kalich5** [comment]
Na 100% jede Nurmi, Medvěd a Kalich

**Comment by kalich5** [comment]
Předběžně NICK, podle toho jak to budou mít doma s novým přírůstkem do rodiny

**Comment by kalich5** [comment]
Předběžně LACHTAN

**Comment by kalich5** [comment]
JÍVA nespíš pojede, tak jsem to z jeho emailu pochopil

**Comment by kalich5** [comment]
Předběžně LIŠKA

**Comment by kalich5** [comment]
Předběžně OUŠKO

**Comment by kalich5** [comment]
PIT se chce také zůčastnit

**Comment by kalich5** [comment]
MARŤAN se chce také zůčastni

**Comment by kalich5** [comment]
Předběžně ZAJÍC (bude to sledovat a ozve se začátkem září)

**Comment by kalich5** [comment]
WEB se chce také zůčastnit
SOVA se chce také zůčastnit

**Comment by kalich5** [comment]
Předběžně PAVOUK

**Comment by kalich5** [comment]
Předběžně DAVY, uvidí jak mu to vyjde

**Comment by Yendy** [comment]
# POTVRDILI
## Pojede:
NICK
ZAJÍC
PIT
KALICH
MEDVĚD
NURMI (pokud se uzdraví) 
WEB
SOVA

## Nepojede:
PAVOUK
LIŠKA
DAVY
OUŠKO
JÍVA
PEDRO
LACHTAN
MAMUT
MARŤAN
