### ISSUE TITLE
Odezva webu

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#6]
Zajistit u webhostingu kontrolu odezvy webu - bývá i několik sekund.

**Comment by Yendy** [comment]
Odeslán e-mail s požadavkem na vylepšení odezvy webu.

**Comment by Yendy** [comment]
Jirka předal dotaz na admina, dá vědět výsledek.

**Comment by kalich5** [comment]
Pořád je to dost pomalé. A to tam ještě nic není. :-(

**Comment by kalich5** [comment]
Co jsem zkoušel teď, tak je to o poznání rychlejší :-) odezva skoro okamžitá :+1:

**Comment by Yendy** [comment]
Řešíme průběžně, zatím to vypadá na cache stránek - občas při změně nabíhají pomaleji.
