### ISSUE TITLE
Objednávka noclehu

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#60]
Přizpůsobit objednávku noclehu skutečnému počtu účastníků.

**Comment by Yendy** [comment]
Jak tohle budeme řešit? Myslím, že je to významný bod pro setkání 28.6. :-)

**Comment by kalich5** [comment]
vyřešil bych 28.6.

**Comment by Yendy** [comment]
Nurmi 10.8. zablokoval 8 míst noclehu.
