### ISSUE TITLE
Itinerář akce (program)

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#62]
Ujasnit si, jak naložíme s časovým prostorem a co chceme získat - snímky, videa (čeho), pamětníky, navštívená místa?

**Comment by kalich5** [comment]
U nás doma byl včera Kvítek a rozhodně říkal ať dojdeme na trojmezí. A že je to nejlepší si kus projít ten "prales" co tam mají. Než jít jen po červené.

**Comment by kalich5** [comment]
Jinak já plánují vzít foťák a drona

**Comment by Yendy** [comment]
Souhlas, trojmezí bychom měli navštívit. Vlastně mě ani jiný cíl spolu s tábořištěm nenapadá. Vezmu videokameru.

**Comment by kalich5** [comment]
Já můžu vzít kameru klidně taky, mám doma malou a docela dobrou

**Comment by Yendy** [comment]
Zjistit, jak je to s pohybem osob v příhraničním pásmu - Kopr mi říkal, že nějak přitvrdili.
