### ISSUE TITLE
Stravování

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#65]
Ujasnit, co budeme po ubytování chtít - plná penze vs. polopenze, večerní prasátko?
Pokud nebudeme chtít plnou penzi, jak zajistíme jídlo?

**Comment by kalich5** [comment]
V Uliči je COOP 
Ulič, 06767, Ulič
Tel.:0915935953
Pondelok 7:00-16:00 
Utorok 7:00-16:00 
Streda 7:00-16:00 
Štvrtok 7:00-16:00 
Piatok 7:00-16:00 
Sobota 7:00-12:00 
Nedeľa Zatvorené

**Comment by Yendy** [comment]
Pokud pojedeme autem, pak nejdůležitější bude objednat večerního kňoura :-).

**Comment by kalich5** [comment]
kaňour to jistí :-)

**Comment by Yendy** [comment]
Zjistit, jak je to penzí/vařením v penzionu.

**Comment by Yendy** [comment]
## Zájemci o snídaně:
### Sobota
Web, Medvěd, Kalich, Nurmi, Zajíc, Pit - všichni
### Neděle
Web, Medvěd, Kalich, Nurmi, Zajíc, Pit - všichni
