### ISSUE TITLE
Přesné umístění tábořiště

### ISSUE THREAD

**Issue by Yendy** [Yendy/petkari.cz#69]
Nejede s námi žádný pamětník. Jak přesně máme tábořiště definováno? GPS?

Pokud si nejsme jisti, měli bychom zapojit pamětníky, aby nám místo upřesnili.

**Comment by kalich5** [comment]
Zkusil bych výroční GONG a na WEBU mapu

**Comment by Yendy** [comment]
Máš výroční GONG? Já ne :-/

**Comment by kalich5** [comment]
Já GONG mám, i v PDF. Můžu ti ho poslat.

**Comment by Yendy** [comment]
Pošli, díky.

**Comment by kalich5** [comment]
https://drive.google.com/drive/u/1/folders/0BxqENvliGlagTmJicDljUnRaQ2s

**Comment by kalich5** [comment]
48.9790881N, 22.4168006E

**Comment by kalich5** [comment]
![ulic](https://user-images.githubusercontent.com/8988898/30337689-6b3c05d4-97e9-11e7-99f1-af83104539db.png)
